#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Dec 11 20:01:55 2020

@author: habibahmed
"""


import numpy as np 
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats


# added to ease the path direction in mac
import os 


path = "~/Python/HousePrice/train.csv"
df_train = pd.read_csv(os.path.expanduser(path))

#df_train.info(verbose=True)

total = df_train.isnull().sum().sort_values(ascending=False)
percent = (df_train.isnull().sum()/df_train.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])

print(missing_data.head(20))

cols_m = ['SalePrice', 'PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu', 'LotFrontage']

for c in cols_m:
    print(c)
    
    #pearson_coef, p_value = stats.pearsonr(df_train[c], df_train['SalePrice'])
    #print('pearson_coef ', pearson_coef)
    #print('p_value ', p_value)